name: FTP Upload
on:
  push:
    branches: [ master ]

jobs:
  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sonomac.co.uk
        ftp-username: adammc@sonomac.co.uk
        ftp-password: letmein2letmein
        local-dir: ./
        git-ftp-args: # optional 
    - uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: http://chat.googleapis.com/v1/spaces/AAAAFc1msp0/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=0erhA9WNJBbWOPvkQOURtK37neNWZnapo7rhcDdCZqQ%3D
        data: "{'txt': 'FTP Deploy ran from Github Actions', 'foo': 'bar'}"

      
