name: FTP Upload
on:
  push:
    branches: [ master ]

jobs:
  my_deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sonomac.co.uk
        ftp-username: adammc
        ftp-password: letmein2letmein
        local-dir: ./
        git-ftp-args: # optional 

    - name: Running Test Echo
      run: echo Hello, world!

      
